#include "instructions_lib.c"
#define NULL 0

struct incsruction {
	char *disassembly;
	unsigned char operandLength;
	void *execute;
} extern const inctruction;

const struct instruction instructions[256] = {
	// 0x
	{ "NOP", 0, NOP },
	{ "LD BC, d16", 2, LD_BC},
	{ "LD (BC), A", 0, NULL},
	{ "INC BC", 0, NULL},
	{ "INC B", 0, NULL},
	{ "DEC B", 0, NULL},
	{ "LD B, d8", 1, NULL},
	{ "RLCA", 0, NULL},
	{ "LD (a16), SP", 2, NULL},
	{ "ADD HL, BC", 0, NULL},
	{ "LD A, (BC)", 0, NULL},
	{ "DEC BC", 0, NULL},
	{ "INC C", 0, NULL},
	{ "DEC C", 0, NULL},
	{ "LD C, d8", 1, NULL},
	{ "RRCA", 0, NULL},
	// 1x
	{ "STOP", 0, NULL },
	{ "LD DE, d16", 2, NULL},
	{ "LD (DE), A", 0, NULL},
	{ "INC DE", 0, NULL},
	{ "INC D", 0, NULL},
	{ "DEC D", 0, NULL},
	{ "LD D, d8", 1, NULL},
	{ "RLA", 0, NULL},
	{ "JR s8", 1, NULL},
	{ "ADD HL, DE", 0, NULL},
	{ "LD A, (DE)", 0, NULL},
	{ "DEC DE", 0, NULL},
	{ "INC E", 0, NULL},
	{ "DEC E", 0, NULL},
	{ "LD E, d8", 1, NULL},
	{ "RRA", 0, NULL},
	// 2x
	{ "JR NZ, s8", 1, NULL },
	{ "LD HL, d16", 2, NULL},
	{ "LD (HL+), A", 0, NULL},
	{ "INC HL", 0, NULL},
	{ "INC H", 0, NULL},
	{ "DEC H", 0, NULL},
	{ "LD H, d8", 1, NULL},
	{ "DAA", 0, NULL},
	{ "JR Z s8", 2, NULL},
	{ "ADD HL, HL", 0, NULL},
	{ "LD A, (HL+)", 0, NULL},
	{ "DEC HL", 0, NULL},
	{ "INC L", 0, NULL},
	{ "DEC L", 0, NULL},
	{ "LD L, d8", 1, NULL},
	{ "CPL", 0, NULL},
	// 3x
	{ "JR NC, s8", 1, NULL },
	{ "LP SP, d16", 2, NULL},
	{ "LD (HL-), A", 0, NULL},
	{ "INC SP", 0, NULL},
	{ "INC (HL)", 2, NULL},
	{ "DEC (HL)", 0, NULL},
	{ "LD (HL), d8", 1, NULL},
	{ "SCF", 0, NULL},
	{ "JR C s8", 2, NULL},
	{ "ADD HL, SP", 0, NULL},
	{ "LD A, (HL-)", 0, NULL},
	{ "DEC SP", 0, NULL},
	{ "INC A", 0, NULL},
	{ "DEC A", 0, NULL},
	{ "LD A, d8", 1, NULL},
	{ "CCF", 0, NULL},
	// 4x
	{ "LD B, B", 0, NULL },
	{ "LD B, C", 0, NULL },
	{ "LD B, D", 0, NULL },
	{ "LD B, E", 0, NULL },
	{ "LD B, H", 0, NULL },
	{ "LD B, L", 0, NULL },
	{ "LD B, (HL)", 0, NULL },
	{ "LD B, A", 0, NULL },
	{ "LD C, B", 0, NULL },
	{ "LD C, C", 0, NULL },
	{ "LD C, D", 0, NULL },
	{ "LD C, E", 0, NULL },
	{ "LD C, H", 0, NULL },
	{ "LD C, L", 0, NULL },
	{ "LD C, (HL)", 0, NULL },
	{ "LD C, A", 0, NULL },
	// 5x
	{ "LD D, B", 0, NULL },
	{ "LD D, C", 0, NULL },
	{ "LD D, D", 0, NULL },
	{ "LD D, E", 0, NULL },
	{ "LD D, H", 0, NULL },
	{ "LD D, L", 0, NULL },
	{ "LD D, (HL)", 0, NULL },
	{ "LD D, A", 0, NULL },
	{ "LD E, B", 0, NULL },
	{ "LD E, C", 0, NULL },
	{ "LD E, D", 0, NULL },
	{ "LD E, E", 0, NULL },
	{ "LD E, H", 0, NULL },
	{ "LD E, L", 0, NULL },
	{ "LD E, (HL)", 0, NULL },
	{ "LD E, A", 0, NULL },
	// 6x
	{ "LD H, B", 0, NULL },
	{ "LD H, C", 0, NULL },
	{ "LD H, D", 0, NULL },
	{ "LD H, E", 0, NULL },
	{ "LD H, H", 0, NULL },
	{ "LD H, L", 0, NULL },
	{ "LD H, (HL)", 0, NULL },
	{ "LD H, A", 0, NULL },
	{ "LD L, B", 0, NULL },
	{ "LD L, C", 0, NULL },
	{ "LD L, D", 0, NULL },
	{ "LD L, E", 0, NULL },
	{ "LD L, H", 0, NULL },
	{ "LD L, L", 0, NULL },
	{ "LD L, (HL)", 0, NULL },
	{ "LD L, A", 0, NULL },
	// 7x
	{ "LD (HL), B", 0, NULL },
	{ "LD (HL), C", 0, NULL },
	{ "LD (HL), D", 0, NULL },
	{ "LD (HL), E", 0, NULL },
	{ "LD (HL), H", 0, NULL },
	{ "LD (HL), L", 0, NULL },
	{ "HALT", 0, NULL },
	{ "LD (HL), A", 0, NULL },
	{ "LD A, B", 0, NULL },
	{ "LD A, C", 0, NULL },
	{ "LD A, D", 0, NULL },
	{ "LD A, E", 0, NULL },
	{ "LD A, H", 0, NULL },
	{ "LD A, L", 0, NULL },
	{ "LD A, (HL)", 0, NULL },
	{ "LD A, A", 0, NULL },
	// 8x
	{ "ADD A, B", 0, NULL },
	{ "ADD A, C", 0, NULL },
	{ "ADD A, D", 0, NULL },
	{ "ADD A, E", 0, NULL },
	{ "ADD A, H", 0, NULL },
	{ "ADD A, L", 0, NULL },
	{ "ADD A, (HL)", 0, NULL },
	{ "ADD A, A", 0, NULL },
	{ "ADC A, B", 0, NULL },
	{ "ADC A, C", 0, NULL },
	{ "ADC A, D", 0, NULL },
	{ "ADC A, E", 0, NULL },
	{ "ADC A, H", 0, NULL },
	{ "ADC A, L", 0, NULL },
	{ "ADC A, (HL)", 0, NULL },
	{ "ADC A, A", 0, NULL },
	// 9x
	{ "SUB B", 0, NULL },
	{ "SUB C", 0, NULL },
	{ "SUB D", 0, NULL },
	{ "SUB E", 0, NULL },
	{ "SUB H", 0, NULL },
	{ "SUB L", 0, NULL },
	{ "SUB (HL)", 0, NULL },
	{ "SUB A", 0, NULL },
	{ "SBC A, B", 0, NULL },
	{ "SBC A, C", 0, NULL },
	{ "SBC A, D", 0, NULL },
	{ "SBC A, E", 0, NULL },
	{ "SBC A, H", 0, NULL },
	{ "SBC A, L", 0, NULL },
	{ "SBC A, (HL)", 0, NULL },
	{ "SBC A, A", 0, NULL },
	// Ax
	{ "AND B", 0, NULL },
	{ "AND C", 0, NULL },
	{ "AND D", 0, NULL },
	{ "AND E", 0, NULL },
	{ "AND H", 0, NULL },
	{ "AND L", 0, NULL },
	{ "AND (HL)", 0, NULL },
	{ "AND A", 0, NULL },
	{ "XOR B", 0, NULL },
	{ "XOR C", 0, NULL },
	{ "XOR D", 0, NULL },
	{ "XOR E", 0, NULL },
	{ "XOR H", 0, NULL },
	{ "XOR L", 0, NULL },
	{ "XOR (HL)", 0, NULL },
	{ "XOR A", 0, NULL },
	// Bx
	{ "OR B", 0, NULL },
	{ "OR C", 0, NULL },
	{ "OR D", 0, NULL },
	{ "OR E", 0, NULL },
	{ "OR H", 0, NULL },
	{ "OR L", 0, NULL },
	{ "OR (HL)", 0, NULL },
	{ "OR A", 0, NULL },
	{ "CP B", 0, NULL },
	{ "CP C", 0, NULL },
	{ "CP D", 0, NULL },
	{ "CP E", 0, NULL },
	{ "CP H", 0, NULL },
	{ "CP L", 0, NULL },
	{ "CP (HL)", 0, NULL },
	{ "CP A", 0, NULL },
	// Cx
	{ "RET NZ", 0, NULL },
	{ "POP BC", 0, NULL },
	{ "JP NZ, a16", 2, NULL },
	{ "JP a16", 2, NULL },
	{ "CALL NZ, a16", 2, NULL },
	{ "PUSH BC", 0, NULL },
	{ "ADD A, d8", 1, NULL },
	{ "RST 00H", 0, NULL },
	{ "RET Z", 0, NULL },
	{ "RET", 0, NULL },
	{ "JP Z, a16", 2, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "CALL Z, a16", 2, NULL },
	{ "CALL a16", 2, NULL },
	{ "ADC A, d8", 1, NULL },
	{ "RST 08H", 0, NULL },
	// Dx
	{ "RET NC", 0, NULL },
	{ "POP DE", 0, NULL },
	{ "JP NC, a16", 2, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "CALL NC, a16", 2, NULL },
	{ "PUSH DE", 0, NULL },
	{ "SUB d8", 1, NULL },
	{ "RST 10H", 0, NULL },
	{ "RET C", 0, NULL },
	{ "RETI", 0, NULL },
	{ "JP C, a16", 2, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "CALL C, a16", 2, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "SBC A, d8", 1, NULL },
	{ "RST 18H", 0, NULL },
	// Ex
	{ "LD (a8), A", 1, NULL },
	{ "POP HL", 0, NULL },
	{ "LD (C), A", 0, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "PUSH HL", 0, NULL },
	{ "AND d8", 1, NULL },
	{ "RST 20H", 0, NULL },
	{ "ADD SP, s8", 1, NULL },
	{ "JP HL", 0, NULL },
	{ "LD (a16), A", 2, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "XOR d8", 1, NULL },
	{ "RST 28H", 0, NULL },
	// Fx
	{ "LD A, (a8)", 1, NULL },
	{ "POP AF", 0, NULL },
	{ "LD A, (C)", 0, NULL },
	{ "DI", 0, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "PUSH AF", 0, NULL },
	{ "OR d8", 1, NULL },
	{ "RST 30H", 0, NULL },
	{ "LD HL, SP+s8", 1, NULL },
	{ "LD SP, HL", 0, NULL },
	{ "LD A, (a16)", 2, NULL },
	{ "EI", 0, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "ILLEGAL", 0, NULL },
	{ "CP d8", 1, NULL },
	{ "RST 38H", 0, NULL }
};